# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ARMMDialog
                                 A QGIS plugin
 ARMM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2023 by GPN_GEO
        email                : nastyashevchenkomail@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtCore import QStringListModel
from PyQt5.QtWidgets import QMainWindow, QListView, QAbstractItemView
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ARMM_dialog_base.ui'))

from PyQt5 import QtCore, QtGui


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        # Required by Qt4 to initialize the UI
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(869, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.cmbLic = QtWidgets.QComboBox(self.centralwidget)
        self.cmbLic.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.cmbLic)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Wellpads = QtWidgets.QWidget()
        self.Wellpads.setObjectName("tab_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.Wellpads)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 490, 841, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.Wellpads)
        self.lineEdit.setGeometry(QtCore.QRect(0, 450, 671, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.listView_wp = QtWidgets.QListView(self.Wellpads)
        self.listView_wp.setGeometry(QtCore.QRect(10, 0, 311, 441))
        self.listView_wp.setObjectName("listView_3")
        self.tableView_2 = QtWidgets.QTableView(self.Wellpads)
        self.tableView_2.setGeometry(QtCore.QRect(340, 0, 501, 441))
        self.tableView_2.setObjectName("tableView_2")
        self.checkBox = QtWidgets.QCheckBox(self.Wellpads)
        self.checkBox.setGeometry(QtCore.QRect(700, 450, 121, 20))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.Wellpads, "")
        self.Rigs = QtWidgets.QWidget()
        self.Rigs.setObjectName("tab_4")
        self.listView_rig = QtWidgets.QListView(self.Rigs)
        self.listView_rig.setGeometry(QtCore.QRect(10, 0, 311, 441))
        self.listView_rig.setObjectName("listView_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Rigs)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 490, 841, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Rigs)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 450, 671, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableView = QtWidgets.QTableView(self.Rigs)
        self.tableView.setGeometry(QtCore.QRect(340, 0, 501, 441))
        self.tableView.setObjectName("tableView")
        self.checkBox_2 = QtWidgets.QCheckBox(self.Rigs)
        self.checkBox_2.setGeometry(QtCore.QRect(700, 450, 121, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tabWidget.addTab(self.Rigs, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Автоматизированное рабочее место маркшейдера"))
        self.label.setText(_translate("MainWindow", "Лицензионный участок"))
        self.pushButton.setText(_translate("MainWindow", "Обновить список лицензионных участков"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить/Изменить"))
        self.checkBox.setText(_translate("MainWindow", "Актуальность"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Wellpads), _translate("MainWindow", "Площадки"))
        self.pushButton_3.setText(_translate("MainWindow", "Изменить"))
        self.checkBox_2.setText(_translate("MainWindow", "Актуальность"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Rigs), _translate("MainWindow", "Станки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Позиции"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Цели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Устья"))
        self.action.setText(_translate("MainWindow", "Добавить"))
        self.action_2.setText(_translate("MainWindow", "Добавить"))
        self.action_3.setText(_translate("MainWindow", "Добавить"))
